# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: Azure-Tansit-VNET-East-West
# label used for menu selection
label: Azure Transit VNET Framework. Step 4 - East West Traffic Segmentation
description: >
               This skillet demonstrates East-West traffic inspection and segmentation thru Hub NGFW’s by configuring Azure UDR’s and corresponding routes, NAT and security policies on VM-Series
# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Azure-Tansit-VNET

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: ew_security_policy_name
    description: East West Security policy name
    default: allow-all-web-dev
    type_hint: text
  - name: src_subnet1_adr_obj
      description: Source Subnet1
      default: dev-subnet
      type_hint: dropdown
      dd_list:
        - key: web-subnet
          value: web-subnet
        - key: app-subnet
          value: app-subnet
        - key: db-subnet
          value: db-subnet
        - key: dev-subnet
          value: dev-subnet
  - name: src_subnet2_adr_obj
      description: Source Subnet2
      default: dev-subnet
      type_hint: dropdown
      dd_list:
        - key: web-subnet
          value: web-subnet
        - key: app-subnet
          value: app-subnet
        - key: db-subnet
          value: db-subnet
        - key: dev-subnet
          value: dev-subnet
  - name: dst_subnet1_adr_obj
      description: Destination Subnet1
      default: dev-subnet
      type_hint: dropdown
      dd_list:
        - key: web-subnet
          value: web-subnet
        - key: app-subnet
          value: app-subnet
        - key: db-subnet
          value: db-subnet
        - key: dev-subnet
          value: dev-subnet
  - name: dst_subnet2_adr_obj
      description: Destination Subnet2
      default: web-subnet
      type_hint: dropdown
      dd_list:
        - key: web-subnet
          value: web-subnet
        - key: app-subnet
          value: app-subnet
        - key: db-subnet
          value: db-subnet
        - key: dev-subnet
          value: dev-subnet
  - name: app_type1
    description: Application type1
      default: web-browsing
      type_hint: dropdown
      dd_list:
        - key: any-application
          value: any
        - key: web
          value: web-browsing
        - key: ssh
          value: ssh
        - key: ping
          value: ping
  - name: app_type2
    description: Application type2 for example any, web-browsing, ssh
        default: ssh
        type_hint: dropdown
        dd_list:
          - key: any-application
            value: any
          - key: web
            value: web-browsing
          - key: ssh
            value: ssh
          - key: ping
            value: ping
  - name: action_type1
    description: Action type allow or deny
        default: allow
        type_hint: dropdown
        dd_list:
          - key: allow
            value: allow
          - key: deny
            value: deny

# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: security_rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
    file: security_rules.xml
  - name: address_objects
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address
    file: address_objects.xml
# ---------------------------------------------------------------------
# end of snippets section
