variable "RGName" {}
variable "KaliRGName" {}
variable "azure_region" {}
variable "ServerKeyName" {}
variable "Admin_Username" {}
variable "Admin_Password" {}
variable "Bootstrap_Storage_Account" {}
variable "Storage_Account_Access_Key" {}
variable "Storage_Account_Fileshare" {}
variable "Storage_Account_Fileshare_Directory" {}
variable "CloudinitscriptPath" {}
variable "KaliinitscriptPath" {}
variable "VNetCIDR" {}
variable "KaliCIDR" {}
variable "WebCIDR_MGMT" {}
variable "WebCIDR_UntrustBlock" {}
variable "WebCIDR_TrustBlock" {}
variable "WebCIDR_AppGWBlock" {}
variable "WebCIDR_WebBlock" {}
variable "attackcidr1" {}
variable "FW_mgmt_IP" {}
variable "FW_Untrust_IP" {}
variable "FW_Trust_IP" {}
variable "WebLB_IP" {}
variable "Web1_IP" {}
variable "Attack_IP" {}